name: bossa
description: A Music Player.

publish_to: 'none'
version: 1.3.0

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^5.0.3
  rxdart: ^0.27.7
  asuka: ^2.0.1+3
  
  file_picker: ^5.2.4
  path_provider: ^2.0.11

  sqflite_common_ffi: ^2.2.0
  sqflite: ^2.2.2
  shared_preferences: ^2.0.17
  
  http: ^0.13.5
  html: ^0.15.1 
  dio: ^4.0.1
  permission_handler: ^8.3.0
  package_info_plus: ^3.0.2
  url_launcher: ^6.1.8
  
  just_audio: ^0.9.30
  just_audio_mpv: ^0.1.6
  just_audio_background: ^0.0.1-beta.9
  just_audio_platform_interface: ^4.1.0
  mpv_dart: ^0.0.1
  audio_session: ^0.1.13
  
  youtube_explode_dart: ^1.10.4
  
  font_awesome_flutter: ^10.3.0
  google_fonts: ^4.0.1
  image: ^4.0.10
  contrast_checker: ^0.0.2
  text_scroll: ^0.1.2

  palette_generator: ^0.3.3+2
  flutter_staggered_grid_view: ^0.6.2
  cached_network_image: ^3.2.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets: 
    - assets/images/disc.png

